#!/bin/bash

# Script for test

echo "=========================="
echo "Homework 5"
echo "=========================="
echo "Username: $(whoami)"
echo "User ID (UID): $UID"
echo "Home Directory: $HOME"
echo "Host Name: $(hostname)"
echo "Terminal Type: $TERM"
echo "=========================="
